### ISSUE TITLE
Portrait mode

### ISSUE THREAD

**Issue by dhasan** [ozboware/javascript-roulette#1]
Hi, and thanks for the great work.

How can we have this game in portrait mode suitable for mobile devices?

**Comment by milsaware** [comment]
The stylesheet will need updating to reorganise the layout for the resolutions you wish to use. Playing itin portrait mode on mobile devices would be difficult for the user, it'd be better if you force the device to be used in landscape mode and even then, there'd need to be more styling done. Currently it's only really compatible with PCs
